PostgreSQLを用いたメモアプリ
Aseiide/memo-sinatra pull request #2
Opened 2021-06-18 12:03 UTC by Aseiide

# スクリーンショット
## 一覧画面

![スクリーンショット 2021-06-18 18 57 04](https://user-images.githubusercontent.com/45246171/122557794-3512a780-d078-11eb-94b1-bb423c76932e.png)

## 新規作成画面

![スクリーンショット 2021-06-18 18 57 10](https://user-images.githubusercontent.com/45246171/122557792-3512a780-d078-11eb-8105-f249f287e298.png)

## 編集画面

![スクリーンショット 2021-06-18 21 03 19](https://user-images.githubusercontent.com/45246171/122558102-a2263d00-d078-11eb-84c6-26ee34b8a74d.png)

## 詳細画面

![スクリーンショット 2021-06-18 18 57 29](https://user-images.githubusercontent.com/45246171/122557790-347a1100-d078-11eb-98e3-0a0d4d71eaf7.png)

2021-06-22 10:14 UTC, u1tnk requested changes

2021-06-22 10:14 UTC, u1tnk commented on README.md
> +3. `bundle install`を実行してください。`Gemfile`と`Gemfile.lock`が生成されます
`Gemfile`と`Gemfile.lock` は生成されるものでは無いのでちょっとおかしいですね。
`Gemfile` で必須gemとかはわかるので 上の Requirements は無くて良いと思います。

2021-06-22 10:14 UTC, u1tnk commented on app.rb
> +  PG.connect(dbname: 'memo_sinatra')
現在の実装だと、毎回接続して実行するようになっています。
postgresqlは接続が結構重いので、もっとsqlが増えると遅くなってしまいます。(実務だと1リクエストで数十sql実行されるのは普通です)
なので、毎回接続しないようにしてみましょう。

2021-06-23 09:10 UTC, Aseiide commented on app.rb
> +  connection = PG.connect(dbname: 'memo_sinatra')
`PG.connect`の返り値を変数に格納することで毎回呼び出さないようにしました。

2021-06-23 11:45 UTC, u1tnk commented on app.rb
> +  connection = PG.connect(dbname: 'memo_sinatra')
これだと毎回呼び出して変数に格納するだけなので、以下二点をやってみてください。

- ローカル以外の変数に入れる
- 変数に入っているときは `PG.connect` しないような処理を入れる

2021-06-23 13:48 UTC, Aseiide commented on app.rb
>  end
> ・ローカル以外の変数に入れる
・変数に入っているときは PG.connect しないような処理を入れる

ご指摘ありがとうございます。
インスタンス変数に入れて、`beforeフィルタ`を使うことでリクエストの前に処理するようにしました。

> ・変数に入っているときは PG.connect しないような処理を入れる

というのがよく分かっておらず、`PG.connect`の返り値を利用するという意味で変数に格納してみました。
この実装でも毎回`@connection.exec`としているので毎回呼び出している事は変わりがないのかなと思っています。

2021-06-24 02:04 UTC, u1tnk commented on app.rb
>  end
いえいえ、これでも大丈夫ですよ。

1. `PG.connect(dbname: 'memo_sinatra')` で接続処理
1. execでクエリ実行

の、接続処理が重く、beforeフィルターはリクエストごとなので、1リクエスト内では再接続しなくなりますので。

アプリ単位で一回にしたいところではありますが、sinatraだとトップレベルにコード書くのでちょっと難しかったですね。これは僕がRailsに慣れててsinatraあんまりやってなかったので難しいと思ってませんでした。すみません 🙏 

対応しなくて良いですが、知識としては

```
class Connect
  def self.get
    return @connection if @connection

    p "init"
    @connection = PG.connect(dbname: 'memo_sinatra')
  end
end

```
こんな感じでクラス変数を利用すればアプリで一個にもできますね。
これを以下みたいに呼び出せば二回目からは `init` が表示されなくなります。

```
  Connect.get
```

2021-06-24 02:04 UTC, u1tnk approved these changes

2021-06-24 22:25 UTC, Aseiide commented on app.rb
>  end
> アプリ単位で一回にしたい
なるほど、アプリ単位で接続を1回にするにはこのように実装すればよいのですね。
あちがとうございます。

2021-06-24 22:45 UTC, merged